### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by AriaFallah** [AriaFallah/mobx-store#3]
* [x] Add localstorage adapter
* [x] Add code coverage
* [x] Create time travel mechanism

**Comment by AriaFallah** [comment]
#4 added local storage

**Comment by AriaFallah** [comment]
#5 adds coverage

**Comment by AriaFallah** [comment]
#6
